### ISSUE TITLE
Por onde começar?

### ISSUE THREAD

**Issue by bmarchete** [etecmaromo/aula1502#1]
@etecmaromo E ai, o que vamos fazer primeiro! Criar o arquivo index.html? 😄

**Comment by etecmaromo** [comment]
@bmarchete Sim, faremos isso.

**Comment by bmarchete** [comment]
👍

**Comment by bmarchete** [comment]
@etecmaromo Index criado, podemos finalizar essa issue?

**Comment by etecmaromo** [comment]
👍
